################ For Standard Env (Working)##################################################################################

# env: standard
# runtime: nodejs20
# service: app-engine-react-demo

# handlers:
#   - url: /static
#     static_dir: build/static

#   - url: /(.*\.(json|ico|js))$
#     static_files: build/\1
#     upload: build/.*\.(json|ico|js)$

#   - url: .*
#     static_files: build/index.html
#     upload: build/index.html


######### For Flexible Env (Working) #################################################
runtime: nodejs
env: flex
service: app-engine-react-demo
runtime_config:
  operating_system: ubuntu22
  # runtime_version: "20"
manual_scaling:
  instances: 1

network:
  name: projects/gcp-poc-11-438104/global/networks/my-vpc
  # instance_ip_mode: internal
#  instance_tag: private-service
  subnetwork_name: subnet1-my-vpc
  # forwarded_ports:
  #   - 9000/tcp

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
  # volumes:
  # - name: ramdisk1
  #   volume_type: tmpfs
  #   size_gb: 0.5

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 15
#   cool_down_period_sec: 180
#   cpu_utilization:
#     target_utilization: 0.6
#   target_concurrent_requests: 100
#################################################################################################################


